import { useMemo, useState } from 'react';
import { Compass, Fish, Flame, Kayak, Mountain, Stars, Trees, Waves } from 'lucide-react';
import { Badge } from '@/components/ui/badge';
import { Card, CardContent } from '@/components/ui/card';
import ListingControls, { type ListingFilters } from '@/components/listing/ListingControls';
import PaginationControls from '@/components/listing/PaginationControls';
import { usePageMetadata } from '@/hooks/usePageMetadata';

const activities = [
  { name: 'Hiking', description: 'Follow quiet forest paths, ridge walks, and family-friendly loops.', locations: ['Pine Ridge', 'Cedar Creek'], image: 'https://images.unsplash.com/photo-1551632811-561732d1e306?auto=format&fit=crop&w=900&q=85', icon: Mountain }, { name: 'Fishing', description: 'Cast from calm shores, docks, and tucked-away creek banks.', locations: ['Lake Haven', 'Bluewater'], image: 'https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=900&q=85', icon: Fish },
  { name: 'Kayaking', description: 'Paddle at your own pace with launches and rentals at select sites.', locations: ['Lake Haven', 'Bluewater'], image: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=900&q=85', icon: Kayak }, { name: 'Campfire nights', description: 'Gather for stories, s’mores, and easy company under the stars.', locations: ['Pine Ridge', 'Lake Haven', 'Bluewater', 'Cedar Creek'], image: 'https://images.unsplash.com/photo-1478131143081-80f7f84ca84d?auto=format&fit=crop&w=900&q=85', icon: Flame },
  { name: 'Nature walks', description: 'Slow down with guided walks that make room for curiosity.', locations: ['Bluewater', 'Cedar Creek'], image: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=900&q=85', icon: Trees }, { name: 'Stargazing', description: 'Look up from dark, open skies after the campfire burns low.', locations: ['Pine Ridge', 'Bluewater'], image: 'https://images.unsplash.com/photo-1464802686167-b939a6910659?auto=format&fit=crop&w=900&q=85', icon: Stars },
  { name: 'Creek exploring', description: 'Spend an afternoon finding skipping stones and small discoveries.', locations: ['Cedar Creek'], image: 'https://images.unsplash.com/photo-1439853949127-fa647821eba0?auto=format&fit=crop&w=900&q=85', icon: Waves }, { name: 'Scenic drives', description: 'Take the long way through mountain, lake, and river country.', locations: ['Pine Ridge', 'Lake Haven'], image: 'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=900&q=85', icon: Compass },
];
export default function Activities() {
  usePageMetadata('Activities — CampFlow', 'Browse Green Valley outdoor activities, from hiking and kayaking to stargazing and campfire nights.');
  const [filters, setFilters] = useState<ListingFilters>({ query: '', sort: 'popularity' });
  const [page, setPage] = useState(1);
  const result = useMemo(() => activities.filter((activity) => `${activity.name} ${activity.locations.join(' ')}`.toLowerCase().includes(filters.query.toLowerCase())).sort((a, b) => filters.sort === 'availability' ? a.locations.length - b.locations.length : a.name.localeCompare(b.name)), [filters]);
  const perPage = 6;
  const visible = result.slice((page - 1) * perPage, page * perPage);
  return <div className="space-y-10 pb-10"><section className="max-w-3xl"><p className="text-sm font-semibold uppercase tracking-[0.16em] text-primary">Get outside</p><h1 className="mt-3 font-serif text-5xl tracking-tight md:text-6xl">Days made for doing less, or more.</h1><p className="mt-5 text-lg leading-8 text-muted-foreground">Choose your own pace, with simple ways to explore at every Green Valley campground.</p></section><ListingControls value={filters} onChange={(next) => { setFilters(next); setPage(1); }} searchPlaceholder="Search activities or campground" sortOptions={[{ value: 'popularity', label: 'A to Z' }, { value: 'availability', label: 'Fewest locations' }]} /><p className="text-sm text-muted-foreground">Showing {visible.length} of {result.length} activities</p><section id="listing" className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">{visible.map(({ name, description, locations, image, icon: Icon }) => <Card key={name} className="overflow-hidden"><img src={image} alt={name} className="h-48 w-full object-cover" /><CardContent className="p-6"><Icon className="h-5 w-5 text-accent" /><h2 className="mt-4 text-xl font-semibold">{name}</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">{description}</p><div className="mt-4 flex flex-wrap gap-2">{locations.map((location) => <Badge key={location} variant="secondary">{location}</Badge>)}</div></CardContent></Card>)}</section><PaginationControls page={page} totalPages={Math.ceil(result.length / perPage)} onPageChange={setPage} /></div>; }
