import { useEffect, useMemo, useState } from 'react';
import { ChevronLeft, ChevronRight } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import { Spinner } from '@/components/ui/spinner';
import ErrorState from '@/components/ui/error-state';
import OperationsStatusBadge from '@/components/operations/OperationsStatusBadge';
import { apiError, labelOf, listReservations, type ApiItem } from '@/services/operationsDashboardService';

const weekdays = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];
const sameDay = (left: Date, right: Date) => left.toISOString().slice(0, 10) === right.toISOString().slice(0, 10);

export default function DashboardAdminCalendar() {
  const [month, setMonth] = useState(() => new Date(new Date().getFullYear(), new Date().getMonth(), 1));
  const [reservations, setReservations] = useState<ApiItem[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  useEffect(() => { const start = new Date(month.getFullYear(), month.getMonth(), 1).toISOString(); const end = new Date(month.getFullYear(), month.getMonth() + 1, 0).toISOString(); setLoading(true); listReservations({ page: 1, limit: 100, checkInFrom: start, checkInTo: end, sort: 'checkIn', order: 'asc' }).then((result) => setReservations(result.data)).catch((caught) => setError(apiError(caught, 'We could not load the booking calendar.'))).finally(() => setLoading(false)); }, [month]);
  const days = useMemo(() => { const firstDay = month.getDay(); const count = new Date(month.getFullYear(), month.getMonth() + 1, 0).getDate(); return Array.from({ length: firstDay + count }, (_, index) => index < firstDay ? null : new Date(month.getFullYear(), month.getMonth(), index - firstDay + 1)); }, [month]);
  const changeMonth = (amount: number) => setMonth((value) => new Date(value.getFullYear(), value.getMonth() + amount, 1));
  if (error) return <ErrorState title="Calendar unavailable" message={error} />;
  return <div className="space-y-6"><section className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-semibold uppercase tracking-[0.16em] text-primary">Operations</p><h1 className="mt-2 font-serif text-4xl tracking-tight">Booking calendar</h1><p className="mt-3 text-muted-foreground">A monthly view of check-ins across your permitted campgrounds.</p></div><div className="flex items-center gap-2"><Button variant="outline" size="icon" onClick={() => changeMonth(-1)}><ChevronLeft className="h-4 w-4" /></Button><p className="min-w-40 text-center font-semibold">{month.toLocaleString(undefined, { month: 'long', year: 'numeric' })}</p><Button variant="outline" size="icon" onClick={() => changeMonth(1)}><ChevronRight className="h-4 w-4" /></Button></div></section><Card className="overflow-hidden">{loading ? <div className="grid min-h-96 place-items-center"><Spinner className="size-6 text-primary" /></div> : <CardContent className="p-0"><div className="grid grid-cols-7 border-b bg-muted/30">{weekdays.map((day) => <p key={day} className="p-3 text-center text-xs font-semibold uppercase tracking-wide text-muted-foreground">{day}</p>)}</div><div className="grid grid-cols-7">{days.map((day, index) => <div key={day?.toISOString() ?? `empty-${index}`} className="min-h-28 border-b border-r p-2 sm:min-h-36">{day && <><p className={sameDay(day, new Date()) ? 'grid h-6 w-6 place-items-center rounded-full bg-primary text-xs font-semibold text-primary-foreground' : 'text-xs font-semibold text-muted-foreground'}>{day.getDate()}</p><div className="mt-2 space-y-1">{reservations.filter((reservation) => sameDay(new Date(reservation.checkIn), day)).slice(0, 3).map((reservation) => <div key={reservation._id} className="rounded-md bg-secondary/70 p-1.5 text-[10px] leading-4 sm:text-xs"><p className="truncate font-semibold">{labelOf(reservation.campsite, 'Campsite')}</p><p className="truncate text-muted-foreground">{reservation.customer?.firstName} {reservation.customer?.lastName}</p></div>)}</div></>}</div>)}</div></CardContent>}</Card><div className="flex flex-wrap gap-3 text-xs text-muted-foreground"><span className="font-medium text-foreground">Showing check-ins</span>{reservations.slice(0, 4).map((reservation) => <span key={reservation._id} className="flex items-center gap-1"><OperationsStatusBadge status={reservation.status} /> {labelOf(reservation.campsite, 'Campsite')}</span>)}</div></div>;
}
