import { useEffect, useState } from 'react';
import { Check, Eye, X } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import { Spinner } from '@/components/ui/spinner';
import ErrorState from '@/components/ui/error-state';
import { DataTable, type DataColumn } from '@/components/operations/DataTable';
import { DataTableControls } from '@/components/operations/DataTableControls';
import { DataTablePagination } from '@/components/operations/DataTablePagination';
import OperationsStatusBadge from '@/components/operations/OperationsStatusBadge';
import { apiError, idOf, labelOf, listReservations, updateReservationStatus, type ApiItem } from '@/services/operationsDashboardService';
import { toast } from 'sonner';

export default function DashboardAdminReservations() {
  const [data, setData] = useState<{ rows: ApiItem[]; page: number; totalPages: number }>({ rows: [], page: 1, totalPages: 1 });
  const [search, setSearch] = useState(''); const [filter, setFilter] = useState('all'); const [sort, setSort] = useState('checkIn'); const [order, setOrder] = useState<'asc' | 'desc'>('asc'); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  const load = (page = data.page) => { setLoading(true); listReservations({ page, limit: 20, search: search || undefined, status: filter === 'all' ? undefined : filter, sort, order }).then((result) => setData({ rows: result.data, page: result.meta.page, totalPages: result.meta.totalPages })).catch((caught) => setError(apiError(caught, 'We could not load reservations.'))).finally(() => setLoading(false)); };
  useEffect(() => { const timer = window.setTimeout(() => load(1), 180); return () => window.clearTimeout(timer); }, [search, filter, sort, order]);
  const changeStatus = async (reservation: ApiItem, status: 'confirmed' | 'cancelled') => { try { await updateReservationStatus(idOf(reservation), status); toast.success(status === 'confirmed' ? 'Booking approved' : 'Booking rejected and cancelled'); load(); } catch (caught) { setError(apiError(caught, 'We could not update this booking.')); } };
  const columns: DataColumn<ApiItem>[] = [{ label: 'Reservation', sortKey: 'createdAt', cell: (row) => <div><p className="font-medium">{row.reservationNumber ?? idOf(row).slice(-6)}</p><p className="text-xs text-muted-foreground">Created {String(row.createdAt ?? '').slice(0, 10)}</p></div> }, { label: 'Guest', cell: (row) => <div><p className="font-medium">{row.customer?.firstName} {row.customer?.lastName}</p><p className="text-xs text-muted-foreground">{row.customer?.email}</p></div> }, { label: 'Stay', sortKey: 'checkIn', cell: (row) => <div><p>{String(row.checkIn).slice(0, 10)}</p><p className="text-xs text-muted-foreground">to {String(row.checkOut).slice(0, 10)} · {labelOf(row.campsite, 'Campsite')}</p></div> }, { label: 'Status', sortKey: 'status', cell: (row) => <OperationsStatusBadge status={row.status} /> }, { label: 'Actions', className: 'text-right', cell: (row) => <div className="flex justify-end gap-1">{row.status === 'pending' && <><Button size="sm" variant="outline" onClick={() => void changeStatus(row, 'confirmed')}><Check />Approve</Button><Button size="sm" variant="outline" onClick={() => void changeStatus(row, 'cancelled')}><X />Reject</Button></>}<Button size="icon" variant="ghost" title="Customer details" onClick={() => document.getElementById(`customer-${idOf(row)}`)?.scrollIntoView({ behavior: 'smooth' })}><Eye className="h-4 w-4" /></Button></div> }];
  return <div className="space-y-6"><section><p className="text-sm font-semibold uppercase tracking-[0.16em] text-primary">Operations</p><h1 className="mt-2 font-serif text-4xl tracking-tight">Reservation management</h1><p className="mt-3 text-muted-foreground">Review booking requests and keep stay statuses current.</p></section>{error && <ErrorState title="Reservations unavailable" message={error} />}<Card className="overflow-hidden"> <DataTableControls search={search} onSearch={setSearch} filter={filter} onFilter={setFilter} filterOptions={[{ value: 'all', label: 'All statuses' }, { value: 'pending', label: 'Pending' }, { value: 'confirmed', label: 'Approved' }, { value: 'cancelled', label: 'Cancelled' }, { value: 'completed', label: 'Completed' }]} placeholder="Search reservation or request…" />{loading ? <div className="grid min-h-64 place-items-center"><Spinner className="size-6 text-primary" /></div> : data.rows.length ? <><DataTable columns={columns} rows={data.rows} rowKey={idOf} onSort={(key) => { setOrder(key === sort && order === 'asc' ? 'desc' : 'asc'); setSort(key); }} /><DataTablePagination page={data.page} totalPages={data.totalPages} onPageChange={load} /></> : <CardContent className="p-10 text-center text-sm text-muted-foreground">No reservations match these controls.</CardContent>}</Card></div>;
}
