import { useEffect, useMemo, useState } from 'react';
import { Eye } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Spinner } from '@/components/ui/spinner';
import ErrorState from '@/components/ui/error-state';
import { DataTable, type DataColumn } from '@/components/operations/DataTable';
import { DataTableControls } from '@/components/operations/DataTableControls';
import { DataTablePagination } from '@/components/operations/DataTablePagination';
import { apiError, getCustomer, idOf, labelOf, listReservations, type ApiItem } from '@/services/operationsDashboardService';
import { useAuth } from '@/hooks/useAuth';

export default function DashboardAdminCustomers() {
  const { user } = useAuth(); const [reservations, setReservations] = useState<ApiItem[]>([]); const [search, setSearch] = useState(''); const [sort, setSort] = useState('name'); const [order, setOrder] = useState<'asc' | 'desc'>('asc'); const [page, setPage] = useState(1); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [customer, setCustomer] = useState<ApiItem | null>(null); const [customerLoading, setCustomerLoading] = useState(false);
  useEffect(() => { setLoading(true); listReservations({ page: 1, limit: 100, sort: 'createdAt', order: 'desc' }).then((result) => setReservations(result.data)).catch((caught) => setError(apiError(caught, 'We could not load customer information.'))).finally(() => setLoading(false)); }, []);
  const customers = useMemo(() => { const entries = new Map<string, ApiItem>(); reservations.forEach((reservation) => { const id = idOf(reservation.customer); if (!id) return; const existing = entries.get(id) ?? { ...reservation.customer, reservations: [] }; existing.reservations.push(reservation); entries.set(id, existing); }); const filtered = [...entries.values()].filter((item) => `${item.firstName} ${item.lastName} ${item.email}`.toLowerCase().includes(search.toLowerCase())); return filtered.sort((left, right) => { const leftValue = sort === 'stays' ? left.reservations.length : `${left.firstName} ${left.lastName}`; const rightValue = sort === 'stays' ? right.reservations.length : `${right.firstName} ${right.lastName}`; return String(leftValue).localeCompare(String(rightValue)) * (order === 'asc' ? 1 : -1); }); }, [reservations, search, sort, order]);
  const totalPages = Math.max(Math.ceil(customers.length / 12), 1); const rows = customers.slice((page - 1) * 12, page * 12);
  useEffect(() => setPage(1), [search, sort, order]);
  const openCustomer = async (item: ApiItem) => { if (user?.role !== 'admin') { setCustomer(item); return; } setCustomerLoading(true); try { setCustomer(await getCustomer(idOf(item))); } catch (caught) { setError(apiError(caught, 'We could not load this customer.')); } finally { setCustomerLoading(false); } };
  const columns: DataColumn<ApiItem>[] = [{ label: 'Customer', sortKey: 'name', cell: (row) => <div><p className="font-medium">{row.firstName} {row.lastName}</p><p className="text-xs text-muted-foreground">{row.email}</p></div> }, { label: 'Reservations', sortKey: 'stays', cell: (row) => `${row.reservations.length} stay${row.reservations.length === 1 ? '' : 's'}` }, { label: 'Latest stay', cell: (row) => { const stay = row.reservations[0]; return <div><p>{String(stay?.checkIn ?? '').slice(0, 10)}</p><p className="text-xs text-muted-foreground">{labelOf(stay?.campground, 'Campground')}</p></div>; } }, { label: '', className: 'text-right', cell: (row) => <Button variant="ghost" size="sm" onClick={() => void openCustomer(row)}><Eye />View</Button> }];
  if (error) return <ErrorState title="Customers unavailable" message={error} />;
  return <div className="space-y-6"><section><p className="text-sm font-semibold uppercase tracking-[0.16em] text-primary">Operations</p><h1 className="mt-2 font-serif text-4xl tracking-tight">Customer information</h1><p className="mt-3 text-muted-foreground">Read-only customer information connected to reservations in your scope.</p></section><Card className="overflow-hidden"><DataTableControls search={search} onSearch={setSearch} filter="all" onFilter={() => undefined} filterOptions={[{ value: 'all', label: user?.role === 'admin' ? 'All customers' : 'Your guests' }]} placeholder="Search customers…" />{loading ? <div className="grid min-h-64 place-items-center"><Spinner className="size-6 text-primary" /></div> : rows.length ? <><DataTable columns={columns} rows={rows} rowKey={idOf} onSort={(key) => { setOrder(key === sort && order === 'asc' ? 'desc' : 'asc'); setSort(key); }} /><DataTablePagination page={page} totalPages={totalPages} onPageChange={setPage} /></> : <CardContent className="p-10 text-center text-sm text-muted-foreground">No customers match this search.</CardContent>}</Card><Dialog open={!!customer || customerLoading} onOpenChange={(open) => !open && setCustomer(null)}><DialogContent><DialogHeader><DialogTitle>Customer details</DialogTitle></DialogHeader>{customerLoading ? <div className="grid min-h-32 place-items-center"><Spinner className="size-6 text-primary" /></div> : customer && <div className="space-y-4 text-sm"><div><p className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">Guest</p><p className="mt-1 text-lg font-semibold">{customer.firstName} {customer.lastName}</p><p className="text-muted-foreground">{customer.email}</p></div>{customer.phone && <div><p className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">Phone</p><p className="mt-1">{customer.phone}</p></div>}{customer.address && <div><p className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">Address</p><p className="mt-1">{[customer.address.street, customer.address.city, customer.address.state, customer.address.zip].filter(Boolean).join(', ')}</p></div>}<p className="rounded-lg bg-secondary/60 p-3 text-muted-foreground">{user?.role === 'admin' ? 'Organization customer profile.' : 'Manager view is limited to contact data included with reservations.'}</p></div>}</DialogContent></Dialog></div>;
}
