import { useMemo, useState } from 'react';
import { ImageIcon } from 'lucide-react';
import { Tabs, TabsList, TabsTrigger } from '@/components/ui/tabs';

const galleryItems = [
  { category: 'rv', title: 'Room to roll in', location: 'Pine Ridge, Colorado', image: 'https://images.unsplash.com/photo-1569134026343-a25e7b09e6ad?auto=format&fit=crop&w=1000&q=85' }, { category: 'tents', title: 'Morning in the pines', location: 'Cedar Creek, Tennessee', image: 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=1000&q=85' },
  { category: 'cabins', title: 'Creekside cabin', location: 'Lake Haven, Michigan', image: 'https://images.unsplash.com/photo-1510798831971-661eb04b3739?auto=format&fit=crop&w=1000&q=85' }, { category: 'activities', title: 'Quiet water, open day', location: 'Bluewater, Oregon', image: 'https://images.unsplash.com/photo-1470252649378-9c29740c9fa8?auto=format&fit=crop&w=1000&q=85' },
  { category: 'rv', title: 'Open road, open sky', location: 'Lake Haven, Michigan', image: 'https://images.unsplash.com/photo-1520190282873-9c6a3a3a4cda?auto=format&fit=crop&w=1000&q=85' }, { category: 'tents', title: 'Campfire hour', location: 'Pine Ridge, Colorado', image: 'https://images.unsplash.com/photo-1478131143081-80f7f84ca84d?auto=format&fit=crop&w=1000&q=85' },
  { category: 'cabins', title: 'A warm welcome', location: 'Cedar Creek, Tennessee', image: 'https://images.unsplash.com/photo-1449157291145-7efd050a4d0e?auto=format&fit=crop&w=1000&q=85' }, { category: 'activities', title: 'Trail time', location: 'Pine Ridge, Colorado', image: 'https://images.unsplash.com/photo-1551632811-561732d1e306?auto=format&fit=crop&w=1000&q=85' },
];
const labels: Record<string, string> = { all: 'All', rv: 'RV', tents: 'Tents', cabins: 'Cabins', activities: 'Activities' };
export default function Gallery() { const [category, setCategory] = useState('all'); const items = useMemo(() => galleryItems.filter((item) => category === 'all' || item.category === category), [category]); return <div className="space-y-10 pb-10"><section className="max-w-3xl"><p className="text-sm font-semibold uppercase tracking-[0.16em] text-primary">Green Valley moments</p><h1 className="mt-3 font-serif text-5xl tracking-tight md:text-6xl">See yourself out here.</h1><p className="mt-5 text-lg leading-8 text-muted-foreground">A look at the places, stays, and small adventures waiting across our four campgrounds.</p></section><Tabs value={category} onValueChange={setCategory}><TabsList className="h-auto flex-wrap justify-start gap-1"><>{Object.entries(labels).map(([value, label]) => <TabsTrigger key={value} value={value}>{label}</TabsTrigger>)}</></TabsList></Tabs><section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{items.map((item) => <figure key={item.title} className="group relative h-72 overflow-hidden rounded-2xl bg-muted"><img src={item.image} alt={item.title} className="h-full w-full object-cover transition duration-500 group-hover:scale-105" /><figcaption className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-black/75 to-transparent px-4 pb-4 pt-14 text-white"><p className="font-semibold">{item.title}</p><p className="mt-1 text-sm text-white/80">{item.location}</p></figcaption></figure>)}</section>{items.length === 0 && <div className="rounded-2xl border border-dashed p-12 text-center text-muted-foreground"><ImageIcon className="mx-auto h-6 w-6" />No photos in this category yet.</div>}</div>; }
