import { useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { CheckCircle2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import { Spinner } from '@/components/ui/spinner';
import ErrorState from '@/components/ui/error-state';
import InvoiceDialog from '@/components/customer/InvoiceDialog';
import { apiError, getReservation, labelOf, type ApiItem } from '@/services/customerDashboardService';
export default function ReservationConfirmation() { const { id } = useParams(); const [reservation, setReservation] = useState<ApiItem | null>(null); const [error, setError] = useState<string | null>(null); useEffect(() => { if (id) getReservation(id).then(setReservation).catch((caught) => setError(apiError(caught, 'We could not load this reservation.'))); }, [id]); if (error) return <ErrorState title="Confirmation unavailable" message={error} />; if (!reservation) return <div className="grid min-h-[50vh] place-items-center"><Spinner className="size-7 text-primary" /></div>; return <div className="mx-auto max-w-2xl py-8"><Card className="text-center"><CardContent className="p-8 sm:p-12"><CheckCircle2 className="mx-auto h-14 w-14 text-primary" /><p className="mt-6 text-sm font-semibold uppercase tracking-[0.16em] text-primary">Reservation confirmed</p><h1 className="mt-3 font-serif text-4xl tracking-tight">You’re headed outside.</h1><p className="mx-auto mt-4 max-w-md leading-7 text-muted-foreground">Your reservation #{reservation.reservationNumber ?? id?.slice(-6)} at {labelOf(reservation.campground, 'Green Valley')} is ready. We’ve added a booking confirmation to your in-app notifications.</p><div className="mx-auto mt-8 max-w-sm rounded-xl bg-secondary p-5 text-left text-sm"><div className="flex justify-between"><span>Arrival</span><span className="font-medium">{String(reservation.checkIn).slice(0, 10)}</span></div><div className="mt-3 flex justify-between"><span>Departure</span><span className="font-medium">{String(reservation.checkOut).slice(0, 10)}</span></div><div className="mt-3 flex justify-between"><span>Total</span><span className="font-semibold">${Number(reservation.pricing?.total ?? 0).toFixed(2)}</span></div></div><div className="mt-8 flex flex-wrap justify-center gap-3"><InvoiceDialog reservation={reservation} /><Button asChild><Link to="/dashboard/bookings">View my bookings</Link></Button></div></CardContent></Card></div>; }
